# Clone the git repo.
steps:
#- name: 'gcr.io/cloud-builders/git'
 # id: 'Clone'
  #args: ['clone', 'https://github.com/AmanM13/cicd_gke']

# This step builds the container image.

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/aman_test_image:latest'
  - '.'
# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/aman_test_image:latest'

# This step generates the new manifest
- name: 'gcr.io/cloud-builders/gcloud'
  id: Generate manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" deployment.yaml.tpl | \
     sed "s/latest/${SHORT_SHA}/g" > deployment.yaml
# This step deploys the new version of our container image
# in the Kubernetes Engine cluster.
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args: ['apply' , '-f' , 'deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=surya-test-cluster-01'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: 
  - '-c'
  - 'docker login --username=$$USERNAME --password=$$PASSWORD'
  secretEnv: ['USERNAME', 'PASSWORD']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/tds-test-2/versions/2
    env: 'PASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/tds-test/versions/2
    env: 'USERNAME'
